# ************************************************************************************************
# Warning: YAML source code for Canvas Apps should only be used to review changes made within Power Apps Studio and for minor edits (Preview).
# Use the maker portal to create and edit your Power Apps.
# 
# The schema file for Canvas Apps is available at https://go.microsoft.com/fwlink/?linkid=2304907
# 
# For more information, visit https://go.microsoft.com/fwlink/?linkid=2292623
# ************************************************************************************************
Screens:
  Training Tracker - MCLE Certificate Chooser:
    Properties:
      LoadingSpinnerColor: =RGBA(56, 96, 178, 1)
    Children:
      - Container12:
          Control: GroupContainer@1.4.0
          Variant: AutoLayout
          Properties:
            Height: =Parent.Height
            LayoutAlignItems: =LayoutAlignItems.Stretch
            LayoutDirection: =LayoutDirection.Vertical
            LayoutGap: =20
            LayoutJustifyContent: =LayoutJustifyContent.SpaceBetween
            Width: =Parent.Width
          Children:
            - Container14_3:
                Control: GroupContainer@1.4.0
                Variant: AutoLayout
                Properties:
                  AlignInContainer: =AlignInContainer.SetByContainer
                  Fill: =fxTheme.Header.BGColor
                  FillPortions: =0
                  Height: ='Background Color_9'.Height
                  LayoutAlignItems: =LayoutAlignItems.Center
                  LayoutDirection: =LayoutDirection.Horizontal
                  PaddingLeft: =20
                  PaddingRight: =20
                  Width: =Parent.Width
                  X: =
                  Y: =
                Children:
                  - Icon11_3:
                      Control: Classic/Icon@2.5.0
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Color: =fxTheme.Header.TextColor
                        Height: =fxTheme.Header.IconSize
                        Icon: =Icon.ArrowLeft
                        OnSelect: =Back();
                        X: =40
                        Y: =40
                  - Label15_4:
                      Control: Label@2.5.1
                      Properties:
                        Align: =Align.Center
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Color: =fxTheme.Header.TextColor
                        Font: =Font.Lato
                        Size: =25
                        Text: ="Generate Certificates"
                        Width: =487
                        X: =(Parent.Width - Self.Width) / 2
                        Y: =15
            - Label19:
                Control: Label@2.5.1
                Properties:
                  BorderColor: =RGBA(0, 18, 107, 1)
                  Font: =Font.'Open Sans'
                  FontWeight: =FontWeight.Semibold
                  PaddingLeft: =30
                  PaddingTop: =30
                  Text: ="Trainings:"
            - ComboBox5:
                Control: Classic/ComboBox@2.4.0
                Properties:
                  AlignInContainer: =AlignInContainer.Center
                  BorderColor: =RGBA(0, 18, 107, 1)
                  ChevronBackground: =RGBA(56, 96, 178, 1)
                  ChevronFill: =RGBA(255, 255, 255, 1)
                  ChevronHoverBackground: =ColorFade(RGBA(56, 96, 178, 1), -20%)
                  ChevronHoverFill: =RGBA(255, 255, 255, 1)
                  DisplayFields: =["ComplianceAssetId"]
                  Font: =Font.'Open Sans'
                  HoverFill: =RGBA(186, 202, 226, 1)
                  IsSearchable: =false
                  Items: =Filter(MCLETrainings, TrainingEndDay <= Now(), "MCLE" in MCLE_Category)
                  LayoutMinWidth: =500
                  OnSelect: =UpdateContext({test2:Filter(MCLETrainingAttendance, TrainingID in ForAll(ComboBox5.SelectedItems, ID), 'Check-InTime' <> Blank(), 'Checkout Time' <> Blank())})
                  PressedColor: =RGBA(255, 255, 255, 1)
                  PressedFill: =RGBA(0, 18, 107, 1)
                  SearchFields: =["ComplianceAssetId"]
                  SelectionColor: =RGBA(255, 255, 255, 1)
                  SelectionFill: =RGBA(56, 96, 178, 1)
                  Width: =Parent.Width - 80
            - Label20:
                Control: Label@2.5.1
                Properties:
                  BorderColor: =RGBA(0, 18, 107, 1)
                  Font: =Font.'Open Sans'
                  FontWeight: =FontWeight.Semibold
                  PaddingLeft: =30
                  PaddingTop: =30
                  Text: ="Attendees:"
            - ComboBox4:
                Control: Classic/ComboBox@2.4.0
                Properties:
                  AlignInContainer: =AlignInContainer.Center
                  BorderColor: =RGBA(0, 18, 107, 1)
                  ChevronBackground: =RGBA(56, 96, 178, 1)
                  ChevronFill: =RGBA(255, 255, 255, 1)
                  ChevronHoverBackground: =ColorFade(RGBA(56, 96, 178, 1), -20%)
                  ChevronHoverFill: =RGBA(255, 255, 255, 1)
                  DisplayFields: =["Name","AttendedTime"]
                  FillPortions: =1
                  Font: =Font.'Open Sans'
                  HoverFill: =RGBA(186, 202, 226, 1)
                  InputTextPlaceholder: ="Select Attendees"
                  IsSearchable: =false
                  Items: |-
                    =ForAll(Filter(MCLETrainingAttendance, TrainingID in ForAll(ComboBox5.SelectedItems, ID), 'Check-InTime' <> Blank(), 'Checkout Time' <> Blank()), {
                        Name: ThisRecord.Attendee,
                        ID: ThisRecord.ID,
                        AttendedTime: Concatenate(Text(DateDiff(ThisRecord.'Check-InTime', ThisRecord.'Checkout Time', TimeUnit.Minutes)), " min"),
                        CO: ThisRecord.'Checkout Time',
                        CI: ThisRecord.'Check-InTime'
                    })
                  OnSelect: |-
                    =UpdateContext({test: Self.SelectedItems})
                  PressedColor: =RGBA(255, 255, 255, 1)
                  PressedFill: =RGBA(0, 18, 107, 1)
                  SearchFields: =["AttendedTime"]
                  SelectionColor: =RGBA(255, 255, 255, 1)
                  SelectionFill: =RGBA(56, 96, 178, 1)
                  Width: =Parent.Width - 80
            - Button1:
                Control: Classic/Button@2.2.0
                Properties:
                  BorderColor: =ColorFade(Self.Fill, -15%)
                  Color: =RGBA(255, 255, 255, 1)
                  DisabledBorderColor: =RGBA(166, 166, 166, 1)
                  Fill: =RGBA(56, 96, 178, 1)
                  Font: =Font.'Open Sans'
                  HoverBorderColor: =ColorFade(Self.BorderColor, 20%)
                  HoverColor: =RGBA(255, 255, 255, 1)
                  HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
                  OnSelect: |-
                    =Navigate('Training Tracker - MCLE Certificate', ScreenTransition.Cover, {AttendanceRecords: ComboBox4.SelectedItems})
                  PressedBorderColor: =Self.Fill
                  PressedColor: =Self.Fill
                  PressedFill: =Self.Color
                  Text: ="Generate Certificates"
