# ************************************************************************************************
# Warning: YAML source code for Canvas Apps should only be used to review changes made within Power Apps Studio and for minor edits (Preview).
# Use the maker portal to create and edit your Power Apps.
# 
# The schema file for Canvas Apps is available at https://go.microsoft.com/fwlink/?linkid=2304907
# 
# For more information, visit https://go.microsoft.com/fwlink/?linkid=2292623
# ************************************************************************************************
Screens:
  Training Tracker - MCLE Certificate Chooser Single:
    Properties:
      LoadingSpinnerColor: =RGBA(56, 96, 178, 1)
      OnHidden: =Reset(ComboBox4_1)
    Children:
      - Container12_1:
          Control: GroupContainer@1.4.0
          Variant: AutoLayout
          Properties:
            Height: =Parent.Height
            LayoutAlignItems: =LayoutAlignItems.Stretch
            LayoutDirection: =LayoutDirection.Vertical
            LayoutGap: =20
            LayoutJustifyContent: =LayoutJustifyContent.SpaceBetween
            Width: =Parent.Width
          Children:
            - Container14_4:
                Control: GroupContainer@1.4.0
                Variant: AutoLayout
                Properties:
                  AlignInContainer: =AlignInContainer.SetByContainer
                  Fill: =fxTheme.Header.BGColor
                  FillPortions: =0
                  Height: ='Background Color_9'.Height
                  LayoutAlignItems: =LayoutAlignItems.Center
                  LayoutDirection: =LayoutDirection.Horizontal
                  Width: ='Background Color_9'.Width
                  X: =
                  Y: =
                Children:
                  - Icon11_4:
                      Control: Classic/Icon@2.5.0
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Color: =fxTheme.Header.TextColor
                        Icon: =Icon.ArrowLeft
                        OnSelect: =Back();
                        X: =40
                        Y: =40
                  - Label15_5:
                      Control: Label@2.5.1
                      Properties:
                        Align: =Align.Center
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Color: =fxTheme.Header.TextColor
                        Font: =Font.Lato
                        Size: =25
                        Text: ="Generate Certificates"
                        Width: =487
                        X: =115
                        Y: =15
            - Label20_1:
                Control: Label@2.5.1
                Properties:
                  BorderColor: =RGBA(0, 18, 107, 1)
                  Font: =Font.'Open Sans'
                  Text: ="Attendees:"
            - ComboBox4_1:
                Control: Classic/ComboBox@2.4.0
                Properties:
                  BorderColor: =RGBA(0, 18, 107, 1)
                  ChevronBackground: =RGBA(56, 96, 178, 1)
                  ChevronFill: =RGBA(255, 255, 255, 1)
                  ChevronHoverBackground: =ColorFade(RGBA(56, 96, 178, 1), -20%)
                  ChevronHoverFill: =RGBA(255, 255, 255, 1)
                  DisplayFields: =["Name","AttendedTime"]
                  FillPortions: =1
                  Font: =Font.'Open Sans'
                  HoverFill: =RGBA(186, 202, 226, 1)
                  Items: |-
                    =ForAll(Filter(MCLETrainingAttendance, TrainingID = Training.ID, 'Check-InTime' <> Blank(), 'Checkout Time' <> Blank()), {
                        Name: ThisRecord.Attendee,
                        ID: ThisRecord.ID,
                        AttendedTime: Concatenate(Text(DateDiff(ThisRecord.'Check-InTime', ThisRecord.'Checkout Time', TimeUnit.Minutes)), " min"),
                        CO: ThisRecord.'Checkout Time',
                        CI: ThisRecord.'Check-InTime'
                    })
                  OnSelect: |-
                    =UpdateContext({test: Self.SelectedItems})
                  PressedColor: =RGBA(255, 255, 255, 1)
                  PressedFill: =RGBA(0, 18, 107, 1)
                  SearchFields: =["AttendedTime"]
                  SelectionColor: =RGBA(255, 255, 255, 1)
                  SelectionFill: =RGBA(56, 96, 178, 1)
            - Button1_1:
                Control: Classic/Button@2.2.0
                Properties:
                  BorderColor: =ColorFade(Self.Fill, -15%)
                  Color: =RGBA(255, 255, 255, 1)
                  DisabledBorderColor: =RGBA(166, 166, 166, 1)
                  Fill: =RGBA(56, 96, 178, 1)
                  Font: =Font.'Open Sans'
                  HoverBorderColor: =ColorFade(Self.BorderColor, 20%)
                  HoverColor: =RGBA(255, 255, 255, 1)
                  HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
                  OnSelect: |-
                    =Navigate('Training Tracker - MCLE Certificate', ScreenTransition.Cover, {AttendanceRecords: ComboBox4_1.SelectedItems})
                  PressedBorderColor: =Self.Fill
                  PressedColor: =Self.Fill
                  PressedFill: =Self.Color
                  Text: ="Generate Certificates"
