# ************************************************************************************************
# Warning: YAML source code for Canvas Apps should only be used to review changes made within Power Apps Studio and for minor edits (Preview).
# Use the maker portal to create and edit your Power Apps.
# 
# The schema file for Canvas Apps is available at https://go.microsoft.com/fwlink/?linkid=2304907
# 
# For more information, visit https://go.microsoft.com/fwlink/?linkid=2292623
# ************************************************************************************************
Screens:
  Training Options:
    Properties:
      LoadingSpinnerColor: =RGBA(56, 96, 178, 1)
    Children:
      - Container2_3:
          Control: GroupContainer@1.4.0
          Variant: AutoLayout
          Properties:
            Height: =Parent.Height
            LayoutDirection: =LayoutDirection.Vertical
            Width: =Parent.Width
            Y: |
              =0
          Children:
            - Container16_4:
                Control: GroupContainer@1.4.0
                Variant: ManualLayout
                Properties:
                  Fill: =RGBA(0, 18, 107, 1)
                  FillPortions: =0
                Children:
                  - TO Request List Screen Header Back_2:
                      Control: Classic/Icon@2.5.0
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Color: =fxTheme.Header.TextColor
                        Height: =70
                        Icon: =Icon.ArrowLeft
                        OnSelect: =Navigate('Home Screen', ScreenTransition.UnCoverRight);
                        Width: =71
                        X: =20
                        Y: =20
                  - Label4_24:
                      Control: Label@2.5.1
                      Properties:
                        Align: =Align.Center
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Color: =RGBA(255, 255, 255, 1)
                        Font: =Font.'Lato Black'
                        FontWeight: =FontWeight.Bold
                        Height: =111
                        Size: =76
                        Text: ="Training"
                        Width: =Parent.Width
                        Y: =(Parent.Height - Self.Height) / 2
            - Container17_3:
                Control: GroupContainer@1.4.0
                Variant: ManualLayout
                Children:
                  - Icon6_5:
                      Control: Classic/Icon@2.5.0
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Color: =RGBA(0, 18, 107, 1)
                        Height: =128
                        Icon: =Icon.AddDocument
                        OnSelect: =Navigate('Training Tracker - ADMIN - Add Training',ScreenTransition.UnCoverRight)
                        Width: =128
                        X: =(Parent.Width - Self.Width) / 2 - 125
                        Y: =137
                  - Icon6_6:
                      Control: Classic/Icon@2.5.0
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Color: =RGBA(0, 18, 107, 1)
                        Height: =128
                        Icon: =Icon.People
                        OnSelect: |-
                          =//Navigate('Time Off Request - Main Screen', ScreenTransition.Cover)
                          Navigate('Training Tracker - Check In',ScreenTransition.Cover)
                        Rotation: =
                        Width: =128
                        X: =(Parent.Width - Self.Width) / 2 + 125
                        Y: =137
                  - Label1_6:
                      Control: Label@2.5.1
                      Properties:
                        Align: =Align.Center
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Font: =Font.'Open Sans'
                        FontWeight: =FontWeight.Semibold
                        OnSelect: =Navigate('TO Request Screen')
                        Text: ="New Training"
                        Width: =204
                        X: =(Parent.Width - Self.Width) / 2 - 125
                        Y: =274
                  - Label1_7:
                      Control: Label@2.5.1
                      Properties:
                        Align: =Align.Center
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Font: =Font.'Open Sans'
                        FontWeight: =FontWeight.Semibold
                        OnSelect: |-
                          =//Navigate('Time Off Request - Main Screen', ScreenTransition.Cover)
                          Navigate('Time Off Request - Admin - View List Screen',ScreenTransition.Cover)
                        Text: ="Check In"
                        Width: =204
                        X: =(Parent.Width - Self.Width) / 2 + 125
                        Y: =274
                  - Icon6_7:
                      Control: Classic/Icon@2.5.0
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Color: =RGBA(0, 18, 107, 1)
                        Height: =128
                        Icon: =Icon.ListWatchlistRemind
                        OnSelect: =Navigate('Training Tracker - Home', ScreenTransition.Cover)
                        Width: =128
                        X: =(Parent.Width - Self.Width) / 2 - 125
                        Y: =384
                  - Label1_8:
                      Control: Label@2.5.1
                      Properties:
                        Align: =Align.Center
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Font: =Font.'Open Sans'
                        FontWeight: =FontWeight.Semibold
                        OnSelect: =Navigate('Training Tracker - Home', ScreenTransition.Cover)
                        Text: ="Training Tracker"
                        Width: =204
                        X: =(Parent.Width - Self.Width) / 2 - 125
                        Y: =521
                  - Icon6_8:
                      Control: Classic/Icon@2.5.0
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Color: =RGBA(0, 18, 107, 1)
                        Height: =128
                        Icon: =Icon.People
                        OnSelect: |-
                          =//Navigate('Time Off Request - Main Screen', ScreenTransition.Cover)
                          Navigate('Training Tracker - Check Out',ScreenTransition.Cover)
                        Rotation: =
                        Width: =128
                        X: =(Parent.Width - Self.Width) / 2 + 125
                        Y: =384
                  - Label1_9:
                      Control: Label@2.5.1
                      Properties:
                        Align: =Align.Center
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Font: =Font.'Open Sans'
                        FontWeight: =FontWeight.Semibold
                        OnSelect: |-
                          =//Navigate('Time Off Request - Main Screen', ScreenTransition.Cover)
                          Navigate('Time Off Request - Admin - View List Screen',ScreenTransition.Cover)
                        Text: ="Check Out"
                        Width: =204
                        X: =(Parent.Width - Self.Width) / 2 + 125
                        Y: =521
                  - Label1_10:
                      Control: Label@2.5.1
                      Properties:
                        Align: =Align.Center
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Font: =Font.'Open Sans'
                        FontWeight: =FontWeight.Semibold
                        OnSelect: =Navigate('Select Report')
                        Text: ="Generate Report"
                        Width: =204
                        X: =219
                        Y: =776
                  - Icon14:
                      Control: Classic/Icon@2.5.0
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Color: =RGBA(0, 18, 107, 1)
                        Height: =128
                        Icon: =Icon.DocumentWithContent
                        OnSelect: =Navigate('Select Report')
                        Width: =128
                        X: =253
                        Y: =636
