# ************************************************************************************************
# Warning: YAML source code for Canvas Apps should only be used to review changes made within Power Apps Studio and for minor edits (Preview).
# Use the maker portal to create and edit your Power Apps.
# 
# The schema file for Canvas Apps is available at https://go.microsoft.com/fwlink/?linkid=2304907
# 
# For more information, visit https://go.microsoft.com/fwlink/?linkid=2292623
# ************************************************************************************************
Screens:
  Training Tracker - Check In:
    Properties:
      LoadingSpinnerColor: =RGBA(56, 96, 178, 1)
    Children:
      - Container1_4:
          Control: GroupContainer@1.4.0
          Variant: AutoLayout
          Properties:
            Height: =Parent.Height
            LayoutDirection: =LayoutDirection.Vertical
            Width: =Parent.Width
          Children:
            - Container3_9:
                Control: GroupContainer@1.4.0
                Variant: AutoLayout
                Properties:
                  Fill: =fxTheme.Header.BGColor
                  LayoutDirection: =LayoutDirection.Horizontal
                Children:
                  - HomeTitle_4:
                      Control: Label@2.5.1
                      Properties:
                        Align: =Align.Center
                        AlignInContainer: =AlignInContainer.Center
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Color: =fxTheme.Header.TextColor
                        Font: =Font.Lato
                        Height: =74
                        Size: =26
                        Text: ="Check-In"
                        Width: =Parent.Width
                        X: =83
                        Y: =127
            - Container4_3:
                Control: GroupContainer@1.4.0
                Variant: AutoLayout
                Properties:
                  FillPortions: =7
                  LayoutDirection: =LayoutDirection.Vertical
                Children:
                  - Container9_1:
                      Control: GroupContainer@1.4.0
                      Variant: ManualLayout
                      Properties:
                        Height: =Parent.Height
                        Width: =Parent.Width
                      Children:
                        - Button7_3:
                            Control: Classic/Button@2.2.0
                            Properties:
                              BorderColor: =ColorFade(Self.Fill, -15%)
                              Color: =RGBA(255, 255, 255, 1)
                              DisabledBorderColor: =RGBA(166, 166, 166, 1)
                              Fill: =RGBA(56, 96, 178, 1)
                              Font: =Font.'Open Sans'
                              Height: =90
                              HoverBorderColor: =ColorFade(Self.BorderColor, 20%)
                              HoverColor: =RGBA(255, 255, 255, 1)
                              HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
                              OnSelect: |-
                                =UpdateContext(
                                    {
                                        MeetingRecord: LookUp(
                                            MCLETrainings,
                                            'Access Code' = TextInput2.Text && ID = _currentSelectedTraining.ID
                                        )
                                    }
                                );
                                If(!IsBlank(LookUp(MCLETrainingAttendance, TrainingID = MeetingRecord.ID && Attendee = User().FullName)),
                                Patch(
                                    MCLETrainingAttendance,
                                    LookUp(
                                        MCLETrainingAttendance,
                                        TrainingID = MeetingRecord.ID && Attendee = User().FullName
                                    ),
                                    {
                                        'Check-InTime': Now(),
                                        Attended: true
                                    }
                                ),
                                Patch(
                                    MCLETrainingAttendance,
                                    Defaults(MCLETrainingAttendance),
                                    {
                                        Attendee: User().FullName,
                                        TrainingID: _currentSelectedTraining.ID,
                                        'Check-InTime': Now(),
                                        Attended: true
                                    }
                                ));
                                Navigate('Training Tracker - Check Out', ScreenTransition.Cover);
                              PressedBorderColor: =Self.Fill
                              PressedColor: =Self.Fill
                              PressedFill: =Self.Color
                              Text: ="Submit Access Code"
                              Width: =Parent.Width - 120
                              X: =60
                              Y: =456
                        - Label11:
                            Control: Label@2.5.1
                            Properties:
                              Align: =Align.Center
                              BorderColor: =RGBA(0, 18, 107, 1)
                              Font: =Font.'Open Sans'
                              FontWeight: =FontWeight.Bold
                              Size: =36
                              Text: ="OR"
                              Width: =100
                              X: =Parent.Width / 2 - Label11.Width / 2
                              Y: =225
                        - TextInput2:
                            Control: Classic/TextInput@2.3.2
                            Properties:
                              BorderColor: =RGBA(0, 18, 107, 1)
                              Default: '=Blank() '
                              Font: =Font.'Open Sans'
                              Format: =TextFormat.Number
                              Height: =74
                              HintText: ="Enter Access Code Here"
                              HoverBorderColor: =RGBA(0, 18, 107, 1)
                              HoverFill: =RGBA(186, 202, 226, 1)
                              MaxLength: =8
                              Width: =Parent.Width - 120
                              X: =60
                              Y: =354
                        - Label12:
                            Control: Label@2.5.1
                            Properties:
                              Align: =Align.Center
                              BorderColor: =RGBA(0, 18, 107, 1)
                              Font: =Font.'Open Sans'
                              Height: =196
                              Text: ="Don't have a QR Code or Access Code? Contact your Training Host."
                              VerticalAlign: =VerticalAlign.Top
                              Width: =520
                              X: =Parent.Width / 2 - Label12.Width / 2
                              Y: =638
                        - BarcodeReader1:
                            Control: BarcodeReader@1.0.25
                            Properties:
                              BorderThickness: =0
                              FontSize: =24
                              Height: =77
                              OnScan: |-
                                =If(!IsBlank(LookUp(MCLETrainingAttendance, Value(Last(BarcodeReader1.Barcodes).Value) = TrainingID && Attendee = User().FullName)),
                                Patch(
                                    MCLETrainingAttendance,
                                    LookUp(
                                        MCLETrainingAttendance,
                                        Value(Last(BarcodeReader1.Barcodes).Value) = TrainingID && Attendee = User().FullName
                                    ),
                                    {
                                        'Check-InTime': Now(),
                                        Attended: true
                                    }
                                ),
                                Patch(
                                    MCLETrainingAttendance,
                                    Defaults(MCLETrainingAttendance),
                                    {
                                        Attendee: User().FullName,
                                        TrainingID: Value(Last(BarcodeReader1.Barcodes).Value),
                                        'Check-InTime': Now(),
                                        Attended: true
                                    }
                                ));


                                Collect(
                                    barCodes,
                                    {
                                        Type: Last(BarcodeReader1.Barcodes).Type,
                                        Value: Last(BarcodeReader1.Barcodes).Value
                                    }
                                )
                              Text: ="Scan QR Code"
                              Width: =Parent.Width - 120
                              X: =60
                              Y: =84
      - Back Button_17:
          Control: Classic/Icon@2.5.0
          Properties:
            BorderColor: =RGBA(0, 18, 107, 1)
            Color: =fxTheme.Header.TextColor
            Height: =fxTheme.Header.IconSize
            Icon: =Icon.ArrowLeft
            OnSelect: =Back();
            Width: =fxTheme.Header.IconSize
            X: =30
            Y: =Container3_9.Height / 2 - 21
