# ************************************************************************************************
# Warning: YAML source code for Canvas Apps should only be used to review changes made within Power Apps Studio and for minor edits (Preview).
# Use the maker portal to create and edit your Power Apps.
# 
# The schema file for Canvas Apps is available at https://go.microsoft.com/fwlink/?linkid=2304907
# 
# For more information, visit https://go.microsoft.com/fwlink/?linkid=2292623
# ************************************************************************************************
Screens:
  Training Tracker - Attendee List:
    Properties:
      LoadingSpinnerColor: =RGBA(56, 96, 178, 1)
    Children:
      - Container12_2:
          Control: GroupContainer@1.4.0
          Variant: AutoLayout
          Properties:
            Height: =Parent.Height
            LayoutAlignItems: =LayoutAlignItems.Stretch
            LayoutDirection: =LayoutDirection.Vertical
            LayoutGap: =20
            LayoutJustifyContent: =LayoutJustifyContent.SpaceBetween
            Width: =Parent.Width
          Children:
            - Container14_5:
                Control: GroupContainer@1.4.0
                Variant: AutoLayout
                Properties:
                  AlignInContainer: =AlignInContainer.SetByContainer
                  Fill: =fxTheme.Header.BGColor
                  FillPortions: =0
                  Height: ='Background Color_9'.Height
                  LayoutAlignItems: =LayoutAlignItems.Center
                  LayoutDirection: =LayoutDirection.Horizontal
                  PaddingLeft: =20
                  PaddingRight: =20
                  Width: ='Background Color_9'.Width
                  X: =
                  Y: =
                Children:
                  - Icon11_5:
                      Control: Classic/Icon@2.5.0
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Color: =fxTheme.Header.TextColor
                        Height: =fxTheme.Header.IconSize
                        Icon: =Icon.ArrowLeft
                        OnSelect: =Back();
                        Width: =fxTheme.Header.IconSize
                        X: =40
                        Y: =40
                  - Label15_6:
                      Control: Label@2.5.1
                      Properties:
                        Align: =Align.Center
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Color: =fxTheme.Header.TextColor
                        Font: =Font.Lato
                        Size: =25
                        Text: ="All Attendees"
                        Width: =487
                        X: =115
                        Y: =15
            - Label20_2:
                Control: Label@2.5.1
                Properties:
                  BorderColor: =RGBA(0, 18, 107, 1)
                  Font: =Font.'Open Sans'
                  Text: ="Attendees:"
            - Gallery5:
                Control: Gallery@2.15.0
                Variant: BrowseLayout_Vertical_TwoTextOneImageVariant_ver5.0
                Properties:
                  BorderColor: =RGBA(0, 18, 107, 1)
                  Items: =Filter(MCLETrainingAttendance, TrainingID = Training.ID)
                Children:
                  - Image2:
                      Control: Image@2.2.3
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Height: =72
                        Image: =LookUp(Users, 'Full Name' = ThisItem.Attendee).'Profile Picture'
                        OnSelect: =Select(Parent)
                        RadiusBottomLeft: =8
                        RadiusBottomRight: =8
                        RadiusTopLeft: =8
                        RadiusTopRight: =8
                        Width: =72
                        X: =16
                        Y: =(Parent.TemplateHeight / 2) - (Self.Height / 2)
                  - Title5:
                      Control: Label@2.5.1
                      Properties:
                        BorderColor: =RGBA(0, 0, 0, 1)
                        Color: =RGBA(50, 49, 48, 1)
                        Font: =Font.'Open Sans'
                        FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                        Height: =Self.Size * 1.8
                        OnSelect: =Select(Parent)
                        PaddingBottom: =0
                        PaddingLeft: =0
                        PaddingRight: =0
                        PaddingTop: =0
                        Size: =14
                        Text: =ThisItem.Title
                        VerticalAlign: =VerticalAlign.Top
                        Width: =Parent.TemplateWidth - 173
                        X: =103
                        Y: =(Parent.TemplateHeight - (Self.Size * 1.8 + Subtitle4.Size * 1.8)) / 2
                  - Subtitle4:
                      Control: Label@2.5.1
                      Properties:
                        BorderColor: =RGBA(0, 0, 0, 1)
                        Font: =Font.'Open Sans'
                        FontWeight: =If(ThisItem.IsSelected, FontWeight.Semibold, FontWeight.Normal)
                        Height: =Self.Size * 1.8
                        OnSelect: =Select(Parent)
                        PaddingBottom: =0
                        PaddingLeft: =0
                        PaddingRight: =0
                        PaddingTop: =0
                        Size: =16
                        Text: =ThisItem.Attendee
                        VerticalAlign: =VerticalAlign.Top
                        Width: =Title5.Width
                        X: =103
                        Y: =37
                  - Separator1:
                      Control: Rectangle@2.3.0
                      Properties:
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Fill: =RGBA(255, 255, 255, 1)
                        Height: =8
                        OnSelect: =Select(Parent)
                        Width: =Parent.TemplateWidth
                        Y: =Parent.TemplateHeight - Self.Height
