# ************************************************************************************************
# Warning: YAML source code for Canvas Apps should only be used to review changes made within Power Apps Studio and for minor edits (Preview).
# Use the maker portal to create and edit your Power Apps.
# 
# The schema file for Canvas Apps is available at https://go.microsoft.com/fwlink/?linkid=2304907
# 
# For more information, visit https://go.microsoft.com/fwlink/?linkid=2292623
# ************************************************************************************************
Screens:
  Training Tracker - RSVP Success:
    Properties:
      LoadingSpinnerColor: =RGBA(56, 96, 178, 1)
    Children:
      - Container1_5:
          Control: GroupContainer@1.4.0
          Variant: AutoLayout
          Properties:
            Height: =Parent.Height
            LayoutDirection: =LayoutDirection.Vertical
            Width: =Parent.Width
          Children:
            - Container3_10:
                Control: GroupContainer@1.4.0
                Variant: AutoLayout
                Properties:
                  Fill: =RGBA(0, 16, 96, 1)
                  LayoutDirection: =LayoutDirection.Horizontal
                Children:
                  - HomeTitle_5:
                      Control: Label@2.5.1
                      Properties:
                        Align: =Align.Center
                        AlignInContainer: =AlignInContainer.Center
                        BorderColor: =RGBA(0, 18, 107, 1)
                        Color: =fxTheme.Header.TextColor
                        Font: =Font.Lato
                        Height: =74
                        Size: =26
                        Text: ="RSVP Success!"
                        Width: =Parent.Width
                        X: =83
                        Y: =127
            - Container4_4:
                Control: GroupContainer@1.4.0
                Variant: AutoLayout
                Properties:
                  FillPortions: =7
                  LayoutDirection: =LayoutDirection.Vertical
                Children:
                  - Container9_2:
                      Control: GroupContainer@1.4.0
                      Variant: ManualLayout
                      Properties:
                        Height: =Parent.Height
                        Width: =Parent.Width
                      Children:
                        - iconCircle2:
                            Control: Circle@2.3.0
                            Properties:
                              BorderColor: =RGBA(0, 18, 107, 1)
                              Fill: =RGBA(56, 96, 178, 1)
                              X: =Parent.Width/2 - Self.Width/2
                              Y: =(Parent.Height/2 - Self.Height/2) * .7
                        - iconCheck2:
                            Control: Classic/Icon@2.5.0
                            Properties:
                              BorderColor: =RGBA(0, 18, 107, 1)
                              Color: =RGBA(255, 255, 255, 1)
                              Height: =iconCircle2.Height
                              Icon: =Icon.Check
                              PaddingBottom: =Self.PaddingTop
                              PaddingLeft: =Self.PaddingTop
                              PaddingRight: =Self.PaddingTop
                              PaddingTop: =18
                              PressedFill: =RGBA(255, 255, 255, 0.3)
                              Width: =iconCircle2.Width
                              X: '=(Parent.Width- Self.Width)/2 '
                              Y: =(Parent.Height/2 - Self.Height/2) * .7
                        - LblSuccessMsg2:
                            Control: Label@2.5.1
                            Properties:
                              Align: =Align.Center
                              AutoHeight: =true
                              BorderColor: =RGBA(0, 18, 107, 1)
                              Font: =Font.'Open Sans'
                              Height: =iconCircle2.Height
                              Text: ="You've been successfully RSVP'd to " & _currentSelectedTraining.Training
                              Width: =Parent.Width * 0.75
                              X: =Parent.Width/2 - Self.Width/2
                              Y: =iconCheck2.Y + iconCheck2.Height + 100
      - Back Button_18:
          Control: Classic/Icon@2.5.0
          Properties:
            BorderColor: =RGBA(0, 18, 107, 1)
            Color: =fxTheme.Header.TextColor
            Height: =fxTheme.Header.IconSize
            Icon: =Icon.ArrowLeft
            OnSelect: =Navigate('Training Tracker - View Training Details', ScreenTransition.Cover)
            Visible: =false
            Width: =fxTheme.Header.IconSize
            X: =30
            Y: =Container3_10.Height / 2 - 21
      - Timer3:
          Control: Timer@2.1.0
          Properties:
            AutoPause: =false
            AutoStart: =true
            BorderColor: =ColorFade(Self.Fill, -15%)
            Color: =RGBA(255, 255, 255, 1)
            DisabledBorderColor: =ColorFade(Self.BorderColor, 70%)
            DisabledColor: =ColorFade(Self.Fill, 90%)
            DisabledFill: =ColorFade(Self.Fill, 70%)
            Duration: =3000
            Fill: =RGBA(56, 96, 178, 1)
            Font: =Font.'Open Sans'
            HoverBorderColor: =ColorFade(Self.BorderColor, 20%)
            HoverColor: =RGBA(255, 255, 255, 1)
            HoverFill: =ColorFade(RGBA(56, 96, 178, 1), -20%)
            OnTimerEnd: =Back(ScreenTransition.UnCoverRight)
            PressedBorderColor: =Self.Fill
            PressedColor: =Self.Fill
            PressedFill: =Self.Color
            Visible: =false
            X: =30
            Y: =190
