"'Training Options' As screen":
    OnVisible: =

    Container2_3 As groupContainer.verticalAutoLayoutContainer:
        Height: =Parent.Height
        LayoutDirection: =LayoutDirection.Vertical
        LayoutGridColumns: =6
        LayoutGridRows: =6
        LayoutMode: =LayoutMode.Auto
        Width: =Parent.Width
        Y: |
            =0
        ZIndex: =1

        Container16_4 As groupContainer.manualLayoutContainer:
            Fill: =RGBA(0, 18, 107, 1)
            FillPortions: =0
            Height: =225
            LayoutGridColumns: =6
            LayoutGridRows: =6
            LayoutMaxHeight: =0
            LayoutMaxWidth: =0
            LayoutMinHeight: =112
            LayoutMinWidth: =250
            ZIndex: =1

            "'TO Request List Screen Header Back_2' As icon.ArrowLeft":
                Color: =fxTheme.Header.TextColor
                Height: =70
                Icon: =Icon.ArrowLeft
                OnSelect: =Navigate('Home Screen', ScreenTransition.UnCoverRight);
                Width: =71
                X: =20
                Y: =20
                ZIndex: =2

            Label4_24 As label:
                Align: =Align.Center
                Color: =RGBA(255, 255, 255, 1)
                Font: =Font.'Lato Black'
                FontWeight: =FontWeight.Bold
                Height: =111
                Size: =76
                Text: ="Training"
                Width: =Parent.Width
                Y: =(Parent.Height - Self.Height) / 2
                ZIndex: =3

        Container17_3 As groupContainer.manualLayoutContainer:
            Height: =225
            LayoutGridColumns: =6
            LayoutGridRows: =6
            LayoutMaxHeight: =0
            LayoutMaxWidth: =0
            LayoutMinHeight: =112
            LayoutMinWidth: =250
            ZIndex: =4

            Icon6_5 As icon.ToolsWrench:
                Height: =128
                Icon: =Icon.AddDocument
                OnSelect: =Navigate('Training Tracker - ADMIN - Add Training',ScreenTransition.UnCoverRight)
                Width: =128
                X: =(Parent.Width - Self.Width) / 2 - 125
                Y: =137
                ZIndex: =5

            Icon6_6 As icon.ToolsWrench:
                Height: =128
                Icon: =Icon.People
                OnSelect: |-
                    =//Navigate('Time Off Request - Main Screen', ScreenTransition.Cover)
                    Navigate('Training Tracker - Check In',ScreenTransition.Cover)
                Rotation: =
                Width: =128
                X: =(Parent.Width - Self.Width) / 2 + 125
                Y: =137
                ZIndex: =6

            Label1_6 As label:
                Align: =Align.Center
                FontWeight: =FontWeight.Semibold
                Height: =70
                OnSelect: =Navigate('TO Request Screen')
                Size: =21
                Text: ="New Training"
                Width: =204
                X: =(Parent.Width - Self.Width) / 2 - 125
                Y: =274
                ZIndex: =7

            Label1_7 As label:
                Align: =Align.Center
                FontWeight: =FontWeight.Semibold
                Height: =70
                OnSelect: |-
                    =//Navigate('Time Off Request - Main Screen', ScreenTransition.Cover)
                    Navigate('Time Off Request - Admin - View List Screen',ScreenTransition.Cover)
                Size: =21
                Text: ="Check In"
                Width: =204
                X: =(Parent.Width - Self.Width) / 2 + 125
                Y: =274
                ZIndex: =8

            Icon6_7 As icon.ToolsWrench:
                Height: =128
                Icon: =Icon.ListWatchlistRemind
                OnSelect: =Navigate('Training Tracker - Home', ScreenTransition.Cover)
                Width: =128
                X: =(Parent.Width - Self.Width) / 2 - 125
                Y: =384
                ZIndex: =9

            Label1_8 As label:
                Align: =Align.Center
                FontWeight: =FontWeight.Semibold
                Height: =70
                OnSelect: =Navigate('Training Tracker - Home', ScreenTransition.Cover)
                Size: =21
                Text: ="Training Tracker"
                Width: =204
                X: =(Parent.Width - Self.Width) / 2 - 125
                Y: =521
                ZIndex: =10

            Icon6_8 As icon.ToolsWrench:
                Height: =128
                Icon: =Icon.People
                OnSelect: |-
                    =//Navigate('Time Off Request - Main Screen', ScreenTransition.Cover)
                    Navigate('Training Tracker - Check Out',ScreenTransition.Cover)
                Rotation: =
                Width: =128
                X: =(Parent.Width - Self.Width) / 2 + 125
                Y: =384
                ZIndex: =11

            Label1_9 As label:
                Align: =Align.Center
                FontWeight: =FontWeight.Semibold
                Height: =70
                OnSelect: |-
                    =//Navigate('Time Off Request - Main Screen', ScreenTransition.Cover)
                    Navigate('Time Off Request - Admin - View List Screen',ScreenTransition.Cover)
                Size: =21
                Text: ="Check Out"
                Width: =204
                X: =(Parent.Width - Self.Width) / 2 + 125
                Y: =521
                ZIndex: =12

            Label1_10 As label:
                Align: =Align.Center
                FontWeight: =FontWeight.Semibold
                Height: =70
                OnSelect: =Navigate('Select Report')
                Size: =21
                Text: ="Generate Report"
                Width: =204
                X: =219
                Y: =776
                ZIndex: =14

            Icon14 As icon.DocumentwithContent:
                Height: =128
                Icon: =Icon.DocumentWithContent
                OnSelect: =Navigate('Select Report')
                Width: =128
                X: =253
                Y: =636
                ZIndex: =15

